CREATE TABLE IF NOT EXISTS mpaFilm (
    mpaId INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT, releaseDate DATE NOT NULL,
    duration INT NOT NULL, mpaId INT NOT NULL,

    CONSTRAINT filmsMpaFilm FOREIGN KEY (mpaId) REFERENCES mpaFilm(mpaId)
);

CREATE TABLE IF NOT EXISTS genrs(
    genreId INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
    userId BIGINT NOT NULL,
    friendId BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,

    CONSTRAINT pk_friendships PRIMARY KEY (userId, friendId),
    CONSTRAINT fk_friendships_initiator FOREIGN KEY (userId) REFERENCES users(id),
    CONSTRAINT fk_friendships_friend FOREIGN KEY (friendId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS filmLikes(
    filmId INT NOT NULL,
    userId INT NOT NULL,

    PRIMARY KEY (filmId, userId),
    CONSTRAINT filmLikesFilm FOREIGN KEY (filmId) REFERENCES films(id),
    CONSTRAINT filmLikesUser FOREIGN KEY (userId) REFERENCES users(id)
);